/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_nio_file_InputFile */

#ifndef _Included_java_nio_file_InputFile
#define _Included_java_nio_file_InputFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_nio_file_InputFile
 * Method:    open
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_java_nio_file_InputFile_open
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     java_nio_file_InputFile
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_nio_file_InputFile_close
  (JNIEnv *, jobject);

/*
 * Class:     java_nio_file_InputFile
 * Method:    readLineNative
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_java_nio_file_InputFile_readLineNative
  (JNIEnv *, jobject);

/*
 * Class:     java_nio_file_InputFile
 * Method:    readFileNative
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_java_nio_file_InputFile_readFileNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
