/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Main_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     Main
 * Method:    some_char
 * Signature: ()[C
 */
JNIEXPORT char* JNICALL Java_Main_some_char
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
