/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InputFile */

#ifndef _Included_InputFile
#define _Included_InputFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InputFile
 * Method:    open
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_InputFile_open
  (JNIEnv *, jobject, char*);

/*
 * Class:     InputFile
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InputFile_close
  (JNIEnv *, jobject);

/*
 * Class:     InputFile
 * Method:    getLineSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_InputFile_getLineSize
  (JNIEnv *, jobject);

/*
 * Class:     InputFile
 * Method:    readCharLine
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_InputFile_readCharLine
  (JNIEnv *, jobject, int);

#ifdef __cplusplus
}
#endif
#endif
